### ISSUE TITLE
support non standard ports?

### ISSUE THREAD

**Issue by fkooman** [silverbucket/webfinger.js#15]
it seems only port 80 and 443 are supported for webfinger calls? I'd be cool if it is possible to use something like 'foo@localhost:8080' in the RS widget...

**Comment by untitaker** [comment]
webfinger.js works fine for me with non-standard ports.

**Comment by fkooman** [comment]
you see activity in your browser console when using foo@localhost:8080?

**Comment by fkooman** [comment]
Aha!

```
Blocked loading mixed active content "http://localhost:8080/.well-known/webfinger?resource=acct:foo@localhost:8080"[Learn More]
```

**Comment by untitaker** [comment]
Yes, I have to disable that.

On 22 November 2015 23:28:30 CET, "François Kooman" <notifications@github.com> wrote:
>Aha!
>
>```
>Blocked loading mixed active content
>"http://localhost:8080/.well-known/webfinger?resource=acct:foo@localhost:8080"[Learn
>More]
>```
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/silverbucket/webfinger.js/issues/15#issuecomment-158809840

-- 
Sent from my phone. Please excuse my brevity.

**Comment by fkooman** [comment]
hmm yeah, that makes things a lot less nice :(

**Comment by untitaker** [comment]
My point is that this isn't a webfinger.js issue, it's just how Firefox behaves. It's also a non-issue outside of development. I tihnk this can be closed.

**Comment by fkooman** [comment]
Agreed.
