### ISSUE TITLE
Lookup doesn't return anything when Webfinger resource is 404

### ISSUE THREAD

**Issue by skddc** [silverbucket/webfinger.js#19]
Please refer to https://github.com/remotestorage/remotestorage.js/issues/937 for the full story. Short version: 404s should be supported and treated as "user doesn't exist on server".

At the moment, this fails without actually failing. You can easily reproduce it by just looking up a non-existing 5apps user address, like so (e.g. with rs.js apps from the browser console):

```js
var webFinger = new WebFinger({tls_only: false, uri_fallback: true, request_timeout: 5000});

webFinger.lookup('therealdoctorfrankenstein@5apps.com', function (err, response) {
  if (err) { console.log('nopadope', err); } else { console.log('yupadup', response) }
});
```

The callback function will never be executed in that case.

**Comment by silverbucket** [comment]
@skddc OK, thanks for reporting this - will probably be able to fix this on Sunday. Sorry for the late response.

**Comment by silverbucket** [comment]
@skddc I am having a look at this now, but am unable to reproduce the problem (or maybe I'm misunderstanding it?) When I lookup a non-existent record, ie. bobby@gmail.com, I get an error object in the callback as expected, just pushed a test. Can you let me know if I'm missing something here?

**Comment by skddc** [comment]
You could try my exact example, because that's what's failing in remoteStorage.js itself as well.

**Comment by silverbucket** [comment]
@skddc ok I think I fixed this, sometimes onreadystatechange wasn't being called, so I added a second handler for onload, and this seems to cover it... can you give it a shot and let me know?

**Comment by skddc** [comment]
Which branch and file should I use?

**Comment by silverbucket** [comment]
@skddc I just published it as v2.4.1

**Comment by skddc** [comment]
I tested this one, and it's throwing errors now. However, it's throwing error objects for every single instance of e.g. the fallback routine. Not sure that's intended or the best API towards app/lib developers.

But it seems to work as intended in remoteStorage.js, except for a different problem, which may or may not be related to the multiple errors. In rs.js I get two `DiscoveryError`s in a row, with a good multiple seconds in between (which both update the widget with a different message). The first says "Failed to contact storage server.", while the second is then correct with ""No storage information found at that user address."

**Comment by silverbucket** [comment]
What types of errors are being thrown? It shouldn't be throwing errors, but
returning Error objects, is the discover.js wrapper perhaps throwing those?
