### ISSUE TITLE
`WebFinger is not a constructor` when loaded with webpack/browserify in browser context

### ISSUE THREAD

**Issue by lesion** [silverbucket/webfinger.js#20]
I have a small issue in the way you are exporting the module:
https://github.com/lesion/webfinger.js/blob/master/src/webfinger.js#L334-L343

You made an initial assumption that if there's a window object, the user wants WebFinger in global window context.
This is not the case with new tools like webpack and browserify that support `commonjs` module definition. 
When using `var WebFinger = require('webfinger.js')` the require is not returning anything because WebFinger loader is exporting itself in `window.WebFinger` but I cannot use that constructor because the variable is overwritten by the assignment itself, so doing `var webFinger = new WebFinger();` is not working as in that scope WebFinger is my variable and not the global exported one and so the error `WebFinger is not a constructor`.

I'll send you a PR for this using a UMD format

**Comment by silverbucket** [comment]
Ah, thanks for the explanation and the patch! Merged, and will bump the release now.
