### ISSUE TITLE
Callback gets called twice

### ISSUE THREAD

**Issue by fenwick67** [silverbucket/webfinger.js#24]
Running this code, the callback get called twice (i.e. I see `got reponse: {...}` twice).  This is basically straight out of the README:

```javascript

var WebFinger = require('webfinger.js');

var webfinger = new WebFinger({
  webfist_fallback: false,  // defaults to false
  tls_only: true,          // defaults to true
  uri_fallback: false,     // defaults to false
  request_timeout: 10000,  // defaults to 10000
});

webfinger.lookup('drew@bumblerexample.pw', function (err, p) {
  if (err) {
    return console.log('error: ', err.message);
  } else {
    return console.log('got response: ',p);
  }
});

```

webfinger.js version: 2.6.4
Node version: 7.5.0
OS: Windows 10

For reference, this is the result from `https://bumblerexample.pw/.well-known/webfinger?resource=acct%3A%40drew%40bumblerexample.pw`:

```
{"subject":"acct:@drew@bumblerexample.pw","links":[{"rel":"http://webfinger.net/rel/avatar","href":"https://bumblerexample.pw/assets/avatar.png"},{"rel":"http://webfinger.net/rel/profile-page","href":"https://bumblerexample.pw/"},{"rel":"http://schemas.google.com/g/2010#updates-from","type":"application/atom+xml","href":"https://bumblerexample.pw/atom.xml"}]}

```

**Comment by silverbucket** [comment]
Hi @fenwick67 I'm currently unable to reproduce this behaviour. Can you show me what the console logs show when this happens? Have you tried on the demo site?: https://silverbucket.github.io/webfinger.js/demo/

**Comment by fenwick67** [comment]
Yup, the demo page does seem to work, this might be specific to the way the `xhr2` module works compared to browsers.

If I had to guess, it might be related to [this code](https://github.com/silverbucket/webfinger.js/blob/master/src/webfinger.js#L147):

```
      xhr.onreadystatechange = function () {
        if (xhr.readyState === 4) {
          __processState();
        }
      };

      xhr.onload = function () {
        __processState();
      };
```

I think both `onload` and `onreadystatechange` get called [( at least, they *should* according to the W3C spec)](https://xhr.spec.whatwg.org/#handle-response-end-of-body).  I can probably debug this tonight.

**Comment by fenwick67** [comment]
The demo page also appears to use an older version (2.1.1) which doesn't register an `onload` callback.

**Comment by silverbucket** [comment]
@fenwick67 ah, thanks for the feedback. Yes you're right about the demo version, I forgot to update it to the newest version. I'm on vacation until middle of next week but will have a look then. In the meantime if you want to submit a pull request I can review/approve from the road.
