### ISSUE TITLE
implement redirect support

### ISSUE THREAD

**Issue by fkooman** [silverbucket/webfinger.js#6]
```
   A WebFinger resource MAY redirect the client; if it does, the
   redirection MUST only be to an "https" URI and the client MUST
   perform certificate validation again when redirected.
```
http://tools.ietf.org/html/rfc7033#section-4.2

Too bad, makes it more complicated. I don't know if you can enforce this checking without writing a for loop and checking the Location header every time?

**Comment by fkooman** [comment]
This is still an issue ;)

**Comment by silverbucket** [comment]
@fkooman bumping to the top of my list to do when i have some free time

**Comment by silverbucket** [comment]
This should be done now, I'm unable to test on a live server though but if the Location header is set with a URL it should work.

**Comment by fkooman** [comment]
Did you enforce the 'https' requirement for the URL in the `Location` header?

```
   A WebFinger resource MAY redirect the client; if it does, the
   redirection MUST only be to an "https" URI and the client MUST
   perform certificate validation again when redirected.
```

**Comment by silverbucket** [comment]
Oops! Thanks for catching that. Will fix soon

**Comment by silverbucket** [comment]
OK this has been added in commit https://github.com/silverbucket/webfinger.js/commit/b6bb32a983d2cffe09c7927de43097c6afac5ce4
